{
  "TeamMentor_Article": {
    "$": {
      "Metadata_Hash": "1505013209",
      "Content_Hash": "-517693959"
    },
    "Metadata": [
      {
        "Id": [
          "26a68d55-95e2-4007-bfa6-d1eee30740de"
        ],
        "Id_History": [
          "26a68d55-95e2-4007-bfa6-d1eee30740de,c00ebef7-6673-4d63-95a3-e469a74150c2,"
        ],
        "Library_Id": [
          "be5273b1-d682-4361-99d9-6234f2d47eb7"
        ],
        "Title": [
          "Deallocation Functions Don't Throw Exceptions"
        ],
        "Category": [
          "Error and Exception Management"
        ],
        "Phase": [
          "Implementation"
        ],
        "Technology": [
          "C++"
        ],
        "Type": [
          "Checklist Item"
        ],
        "DirectLink": [
          "Deallocation Functions Don't Throw Exceptions"
        ],
        "Tag": [
          ""
        ],
        "Security_Demand": [
          ""
        ],
        "Author": [
          ""
        ],
        "Priority": [
          ""
        ],
        "Status": [
          ""
        ],
        "Source": [
          "SI"
        ]
      }
    ],
    "Content": [
      {
        "$": {
          "Sanitized": "true",
          "DataType": "Html"
        },
        "Data": [
          "<h1>Applies to</h1>\r\n  <ul>\r\n    <li>C&#43;&#43;</li>\r\n  </ul>\r\n  <h1>What to Check For</h1>\r\n  <p>Verify that deallocation functions don't throw exceptions.</p>\r\n  <h1>Why</h1>\r\n  <p>Deallocation functions may be called when exceptions are thrown. If a deallocation function throws an exception after being called when an exception is thrown, the program may terminate. This may result in a denial-of-service vulnerability.</p>\r\n  <h1>How to Check</h1>\r\n  <p>Search for deallocation functions. Verify that deallocation functions don't throw exceptions.</p>\r\n  <h1>How to Fix</h1>\r\n  <p>Identify deallocation functions that throw exceptions and rewrite them in such a way that they don't throw exceptions.</p>\r\n  <h1>Additional Resources</h1>\r\n  <ul>\r\n    <li>For more information about not throwing exceptions from deallocation functions, please see <a href=\"https://www.securecoding.cert.org/confluence/display/cplusplus/ERR38-CPP.&#43;Deallocation&#43;functions&#43;must&#43;not&#43;throw&#43;exceptions\">https://www.securecoding.cert.org/confluence/display/cplusplus/ERR38-CPP.&#43;Deallocation&#43;functions&#43;must&#43;not&#43;throw&#43;exceptions</a></li>\r\n  </ul>\r\n  <h1>Related Items</h1>\r\n  <ul>\r\n    <li>\r\n      <a href=\"/article/441b4138-1866-442f-8abb-6d05236d6fcb\">Don't Throw Exceptions from Deallocation Functions</a>\r\n      <li>\r\n        <a href=\"/article/fd06b089-88ea-43df-bc41-f111a1848116\">Don't Throw Exceptions from Destructors</a>\r\n        <li>\r\n          <a href=\"/article/2e732e9d-5677-40cc-8e33-c40ceacc056b\">\r\n            <a href=\"/article/2e732e9d-5677-40cc-8e33-c40ceacc056b\">Destructors don't throw exceptions</a>\r\n          </a>\r\n        </li>\r\n      </li>\r\n    </li>\r\n  </ul>"
        ]
      }
    ]
  }
}