{
  "TeamMentor_Article": {
    "$": {
      "Metadata_Hash": "1269446204",
      "Content_Hash": "867560712"
    },
    "Metadata": [
      {
        "Id": [
          "2e732e9d-5677-40cc-8e33-c40ceacc056b"
        ],
        "Id_History": [
          "2e732e9d-5677-40cc-8e33-c40ceacc056b,1ab3c221-6915-4f17-8c09-630f903ed709,"
        ],
        "Library_Id": [
          "be5273b1-d682-4361-99d9-6234f2d47eb7"
        ],
        "Title": [
          "Destructors Don't Throw Exceptions"
        ],
        "Category": [
          "Error and Exception Management"
        ],
        "Phase": [
          "Implementation"
        ],
        "Technology": [
          "Technology Independent"
        ],
        "Type": [
          "Checklist Item"
        ],
        "DirectLink": [
          "Destructors Don't Throw Exceptions"
        ],
        "Tag": [
          ""
        ],
        "Security_Demand": [
          ""
        ],
        "Author": [
          ""
        ],
        "Priority": [
          ""
        ],
        "Status": [
          ""
        ],
        "Source": [
          "SI"
        ]
      }
    ],
    "Content": [
      {
        "$": {
          "Sanitized": "true",
          "DataType": "html"
        },
        "Data": [
          "<h1>What to Check For</h1>\r\n  <p>Verify that destructors don't throw exceptions if they are called when an exception is thrown. The best way to do this is by not throwing exceptions from destructors.</p>\r\n  <h1>Why</h1>\r\n  <p>A destructor may be called when an exception is thrown. If a destructor throws an exception after being called from an exception being thrown, the program is likely to terminate. This may result in a denial-of-service vulnerability.</p>\r\n  <h1>How to Check</h1>\r\n  <p>Search for destructors. Verify that destructors don't throw exceptions when they are called as a result of other exceptions being thrown. The simplest way to do this is by not throwing exceptions from destructors.</p>\r\n  <h1>How to Fix</h1>\r\n  <p>Identify destructors that throw exceptions. Rewrite code so that destructors don't throw exceptions.</p>\r\n  <h1>Additional Resources</h1>\r\n  <ul>\r\n    <li>For more information about not throwing exceptions from destructors, see <a href=\"https://www.securecoding.cert.org/confluence/display/cplusplus/DCL58-CPP.+Destructors+and+deallocation+functions+must+be+declared+noexcept\">https://www.securecoding.cert.org/confluence/display/cplusplus/DCL58-CPP.+Destructors+and+deallocation+functions+must+be+declared+noexcept</a></li>\r\n  </ul>"
        ]
      }
    ]
  }
}