<h1>Applies to</h1>
  <p>C&#43;&#43;</p>
  <h1>What to Check For</h1>
  <p>Verify that destructors don't throw exceptions if they are called when an exception is thrown. The best way to do this is by not throwing exceptions from destructors.</p>
  <h1>Why</h1>
  <p>A destructor may be called when an exception is thrown. If a destructor throws an exception after being called from an exception being thrown, the program is likely to terminate. This may result in a denial-of-service vulnerability.</p>
  <h1>How to Check</h1>
  <p>Search for destructors. Verify that destructors don't throw exceptions when they are called as a result of other exceptions being thrown. The simplest way to do this is by not throwing exceptions from destructors.</p>
  <h1>How to Fix</h1>
  <p>Identify destructors that throw exceptions. Rewrite code so that destructors don't throw exceptions.</p>
  <h1>Additional Resources</h1>
  <ul>
    <li>For more information about not throwing exceptions from destructors, please see <a href="https://www.securecoding.cert.org/confluence/display/cplusplus/VOID+ERR33-CPP.+Destructors+must+not+throw+exceptions">https://www.securecoding.cert.org/confluence/display/cplusplus/VOID+ERR33-CPP.+Destructors+must+not+throw+exceptions</a></li>
  </ul>
  <h1>Related Items</h1>
  <ul>
    <li>
      <a href="/article/fd06b089-88ea-43df-bc41-f111a1848116">Don't Throw Exceptions from Destructors</a>
      <li>
        <a href="/article/441b4138-1866-442f-8abb-6d05236d6fcb">Don't Throw Exceptions from Deallocation Functions</a>
        <li>
          <a href="/article/26a68d55-95e2-4007-bfa6-d1eee30740de">Deallocation functions don't throw exceptions<br /></a>
        </li>
      </li>
    </li>
  </ul>